<?php
/**
 * TaskTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Wrike\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wrike REST API
 *
 * Definition of the [Wrike API 3.0](https://developers.wrike.com/documentation/api/overview).
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Wrike\Client;

/**
 * TaskTest Class Doc Comment
 *
 * @category    Class */
// * @description Task
/**
 * @package     Wrike\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TaskTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Task"
     */
    public function testTask()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "accountid"
     */
    public function testPropertyAccountid()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "brief_description"
     */
    public function testPropertyBriefDescription()
    {

    }

    /**
     * Test attribute "parent_ids"
     */
    public function testPropertyParentIds()
    {

    }

    /**
     * Test attribute "super_parent_ids"
     */
    public function testPropertySuperParentIds()
    {

    }

    /**
     * Test attribute "shared_ids"
     */
    public function testPropertySharedIds()
    {

    }

    /**
     * Test attribute "responsible_ids"
     */
    public function testPropertyResponsibleIds()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

    /**
     * Test attribute "importance"
     */
    public function testPropertyImportance()
    {

    }

    /**
     * Test attribute "created_date"
     */
    public function testPropertyCreatedDate()
    {

    }

    /**
     * Test attribute "updated_date"
     */
    public function testPropertyUpdatedDate()
    {

    }

    /**
     * Test attribute "dates"
     */
    public function testPropertyDates()
    {

    }

    /**
     * Test attribute "scope"
     */
    public function testPropertyScope()
    {

    }

    /**
     * Test attribute "author_ids"
     */
    public function testPropertyAuthorIds()
    {

    }

    /**
     * Test attribute "custom_status_id"
     */
    public function testPropertyCustomStatusId()
    {

    }

    /**
     * Test attribute "has_attachments"
     */
    public function testPropertyHasAttachments()
    {

    }

    /**
     * Test attribute "attachment_count"
     */
    public function testPropertyAttachmentCount()
    {

    }

    /**
     * Test attribute "permalink"
     */
    public function testPropertyPermalink()
    {

    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {

    }

    /**
     * Test attribute "super_task_ids"
     */
    public function testPropertySuperTaskIds()
    {

    }

    /**
     * Test attribute "sub_task_ids"
     */
    public function testPropertySubTaskIds()
    {

    }

    /**
     * Test attribute "dependency_ids"
     */
    public function testPropertyDependencyIds()
    {

    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {

    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {

    }

}
