<?php
/**
 * TimelogTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Wrike\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wrike REST API
 *
 * Definition of the [Wrike API 3.0](https://developers.wrike.com/documentation/api/overview).
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Wrike\Client;

/**
 * TimelogTest Class Doc Comment
 *
 * @category    Class */
// * @description Timelog
/**
 * @package     Wrike\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TimelogTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Timelog"
     */
    public function testTimelog()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "task_id"
     */
    public function testPropertyTaskId()
    {

    }

    /**
     * Test attribute "user_id"
     */
    public function testPropertyUserId()
    {

    }

    /**
     * Test attribute "hours"
     */
    public function testPropertyHours()
    {

    }

    /**
     * Test attribute "created_date"
     */
    public function testPropertyCreatedDate()
    {

    }

    /**
     * Test attribute "tracked_date"
     */
    public function testPropertyTrackedDate()
    {

    }

    /**
     * Test attribute "comment"
     */
    public function testPropertyComment()
    {

    }

}
