<?php
/**
 * DefaultApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Wrike\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Wrike REST API
 *
 * Definition of the [Wrike API 3.0](https://developers.wrike.com/documentation/api/overview).
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Wrike\Client;

use \Wrike\Client\Configuration;
use \Wrike\Client\ApiClient;
use \Wrike\Client\ApiException;
use \Wrike\Client\ObjectSerializer;

/**
 * DefaultApiTest Class Doc Comment
 *
 * @category Class
 * @package  Wrike\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DefaultApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for getContacts
     *
     * .
     *
     */
    public function testGetContacts()
    {

    }

    /**
     * Test case for getContactsById
     *
     * .
     *
     */
    public function testGetContactsById()
    {

    }

    /**
     * Test case for getFolders
     *
     * .
     *
     */
    public function testGetFolders()
    {

    }

    /**
     * Test case for getFoldersFromFolderId
     *
     * .
     *
     */
    public function testGetFoldersFromFolderId()
    {

    }

    /**
     * Test case for getTasks
     *
     * .
     *
     */
    public function testGetTasks()
    {

    }

    /**
     * Test case for getTasksById
     *
     * .
     *
     */
    public function testGetTasksById()
    {

    }

    /**
     * Test case for getTimelogs
     *
     * .
     *
     */
    public function testGetTimelogs()
    {

    }

    /**
     * Test case for getTimelogsForAccount
     *
     * .
     *
     */
    public function testGetTimelogsForAccount()
    {

    }

    /**
     * Test case for getTimelogsForContact
     *
     * .
     *
     */
    public function testGetTimelogsForContact()
    {

    }

    /**
     * Test case for getTimelogsForFolder
     *
     * .
     *
     */
    public function testGetTimelogsForFolder()
    {

    }

    /**
     * Test case for getTimelogsForTask
     *
     * .
     *
     */
    public function testGetTimelogsForTask()
    {

    }

    /**
     * Test case for updateMyContact
     *
     * .
     *
     */
    public function testUpdateMyContact()
    {

    }

}
